export const CALL_CAMPAIGN_LIST_REQUEST = 'CALL_CAMPAIGN_LIST_REQUEST'
export const CALL_CAMPAIGN_LIST_SUCCESS = 'CALL_CAMPAIGN_LIST_SUCCESS'
export const CALL_CAMPAIGN_LIST_ERROR = 'CALL_CAMPAIGN_LIST_ERROR'

export const CAMPAIGN_SEARCHING_REQUEST = 'CAMPAIGN_SEARCHING_REQUEST'
export const CAMPAIGN_SEARCHING_SUCCESS = 'CAMPAIGN_SEARCHING_SUCCESS'
export const CAMPAIGN_SEARCHING_ERROR = 'CAMPAIGN_SEARCHING_ERROR'

export const CAMPAIGN_CREATING_REQUEST = 'CAMPAIGN_CREATING_REQUEST'
export const CAMPAIGN_CREATING_SUCCESS = 'CAMPAIGN_CREATING_SUCCESS'
export const CAMPAIGN_CREATING_ERROR = 'CAMPAIGN_CREATING_ERROR'

export const CAMPAIGN_UPDATING_REQUEST = 'CAMPAIGN_UPDATING_REQUEST'
export const CAMPAIGN_UPDATING_SUCCESS = 'CAMPAIGN_UPDATING_SUCCESS'
export const CAMPAIGN_UPDATING_ERROR = 'CAMPAIGN_UPDATING_ERROR'

export const CAMPAIGN_DELETING_REQUEST = 'CAMPAIGN_DELETING_REQUEST'
export const CAMPAIGN_DELETING_SUCCESS = 'CAMPAIGN_DELETING_SUCCESS'
export const CAMPAIGN_DELETING_ERROR = 'CAMPAIGN_DELETING_ERROR'

export const CALL_CAMPAIGN_DETAIL_FORM_REQUEST = 'CALL_CAMPAIGN_DETAIL_FORM_REQUEST'
export const CALL_CAMPAIGN_DETAIL_FORM_SUCCESS = 'CALL_CAMPAIGN_DETAIL_FORM_SUCCESS'
export const CALL_CAMPAIGN_DETAIL_FORM_ERROR = 'CALL_CAMPAIGN_DETAIL_FORM_ERROR'

export const TURN_OFF_CALL_CAMPAIGN_DIALOG = 'TURN_OFF_CALL_CAMPAIGN_DIALOG'