export const ORDER_CREATING_REQUEST = 'ORDER_CREATING_REQUEST'
export const ORDER_CREATING_SUCCESS = 'ORDER_CREATING_SUCCESS'
export const ORDER_CREATING_ERROR = 'ORDER_CREATING_ERROR'

export const TURN_OFF_ORDER_DIALOG = 'TURN_OFF_ORDER_DIALOG'
export const TURN_OFF_CAMPAIGN_ORDER_DIALOG = 'TURN_OFF_CAMPAIGN_ORDER_DIALOG'

export const ORDER_UPDATING_REQUEST = 'ORDER_UPDATING_REQUEST'
export const ORDER_UPDATING_SUCCESS = 'ORDER_UPDATING_SUCCESS'
export const ORDER_UPDATING_ERROR = 'ORDER_UPDATING_ERROR'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_RESET = 'ORDER_LIST_RESET'
export const ORDER_LIST_ERROR = 'ORDER_LIST_ERROR'

export const ORDER_CAMPAIGN_LIST_REQUEST = 'ORDER_CAMPAIGN_LIST_REQUEST'
export const ORDER_CAMPAIGN_LIST_SUCCESS = 'ORDER_CAMPAIGN_LIST_SUCCESS'
export const ORDER_CAMPAIGN_LIST_RESET = 'ORDER_CAMPAIGN_LIST_RESET'
export const ORDER_CAMPAIGN_LIST_ERROR = 'ORDER_CAMPAIGN_LIST_ERROR'

export const ORDER_FINDING_FOR_TABLE_REQUEST = 'ORDER_FINDING_FOR_TABLE_REQUEST'
export const ORDER_FINDING_FOR_TABLE_SUCCESS = 'ORDER_FINDING_FOR_TABLE_SUCCESS'
export const ORDER_FINDING_FOR_TABLE_ERROR = 'ORDER_FINDING_FOR_TABLE_ERROR'
export const ORDER_FINDING_FOR_TABLE_RESET= 'ORDER_FINDING_FOR_TABLE_RESET'

export const ORDER_FINDING_REQUEST = 'ORDER_FINDING_REQUEST'
export const ORDER_FINDING_SUCCESS = 'ORDER_FINDING_SUCCESS'
export const ORDER_FINDING_ERROR = 'ORDER_FINDING_ERROR'

export const ORDER_FILTER_FINDING_REQUEST = 'ORDER_FILTER_FINDING_REQUEST'
export const ORDER_FILTER_FINDING_SUCCESS = 'ORDER_FILTER_FINDING_SUCCESS'
export const ORDER_FILTER_FINDING_ERROR = 'ORDER_FILTER_FINDING_ERROR'

export const ORDER_LIST_SCHEDULE_REQUEST = 'ORDER_LIST_SCHEDULE_REQUEST'
export const ORDER_LIST_SCHEDULE_SUCCESS = 'ORDER_LIST_SCHEDULE_SUCCESS'
export const ORDER_LIST_SCHEDULE_ERROR = 'ORDER_LIST_SCHEDULE_ERROR'

export const ORDER_CAMPAIGN_LIST_SCHEDULE_REQUEST = 'ORDER_CAMPAIGN_LIST_SCHEDULE_REQUEST'
export const ORDER_CAMPAIGN_LIST_SCHEDULE_SUCCESS = 'ORDER_CAMPAIGN_LIST_SCHEDULE_SUCCESS'
export const ORDER_CAMPAIGN_LIST_SCHEDULE_ERROR = 'ORDER_CAMPAIGN_LIST_SCHEDULE_ERROR'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_ERROR = 'ORDER_DETAIL_ERROR'
export const ORDER_DETAIL_RESET = 'ORDER_DETAIL_RESET'

export const ORDER_DETAIL_FORM_REQUEST = 'ORDER_DETAIL_FORM_REQUEST'
export const ORDER_DETAIL_FORM_SUCCESS = 'ORDER_DETAIL_FORM_SUCCESS'
export const ORDER_DETAIL_FORM_ERROR = 'ORDER_DETAIL_FORM_ERROR'

export const ORDER_CAMPAIGN_DETAIL_FORM_REQUEST = 'ORDER_CAMPAIGN_DETAIL_FORM_REQUEST'
export const ORDER_CAMPAIGN_DETAIL_FORM_SUCCESS = 'ORDER_CAMPAIGN_DETAIL_FORM_SUCCESS'
export const ORDER_CAMPAIGN_DETAIL_FORM_ERROR = 'ORDER_CAMPAIGN_DETAIL_FORM_ERROR'

export const TEMPORARY_ORDER_SAVING_REQUEST = 'TEMPORARY_ORDER_SAVING_REQUEST'