export const SET_ENABLE = 'SET_ENABLE'

export const SESSION = 'SESSION'

export const OPEN_WINDOW = 'OPEN_WINDOW'
export const OPEN_CALL_BOX = 'OPEN_CALL_BOX'
export const OPEN_DIAL_PAD = 'OPEN_DIAL_PAD'

export const CLOSE_WINDOW = 'CLOSE_WINDOW'
export const CLOSE_CALL_BOX = 'CLOSE_CALL_BOX'
export const CLOSE_DIAL_PAD = 'CLOSE_DIAL_PAD'

export const UPDATE_CALL_ID = 'UPDATE_CALL_ID'
export const CALL_UPDATING_REQUEST = 'CALL_UPDATING_REQUEST'
export const UPDATE_ORDER_ID = 'UPDATE_ORDER_ID'
export const UPDATE_ORDER_CONTENT = 'UPDATE_ORDER_CONTENT'

export const OUTCOMING_REQUEST = 'OUTCOMING_REQUEST'
export const OUTCOMING_CONNECTED = 'OUTCOMING_CONNECTED'
export const OUTCOMING_RESPONSE = 'OUTCOMING_RESPONSE'
export const OUTCOMING_END = 'OUTCOMING_END'
export const OUTCOMING_FAIL = 'OUTCOMING_FAIL'

export const INCOMING_REQUEST = 'INCOMING_REQUEST'
export const INCOMING_RESPONSE = 'INCOMING_RESPONSE'
export const INCOMING_END = 'INCOMING_END'
export const INCOMING_FAIL = 'INCOMING_FAIL'

export const SET_VOLUME = 'SET_VOLUME'

export const RESET_DETAIL = 'RESET_DETAIL'
export const BY_EMPLOYEE = 'BY_EMPLOYEE'