export const NEW_NOTIFICATION_REQUEST = 'NEW_NOTIFICATION_REQUEST'
export const NEW_NOTIFICATION_SUCCESS = 'NEW_NOTIFICATION_SUCCESS'
export const NEW_NOTIFICATION_ERROR = 'NEW_NOTIFICATION_ERROR'

export const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST'
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS'
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR'

export const NOTIFICATION_UPDATING_REQUEST = 'NOTIFICATION_UPDATING_REQUEST'
export const NOTIFICATION_UPDATING_SUCCESS = 'NOTIFICATION_UPDATING_SUCCESS'
export const NOTIFICATION_UPDATING_ERROR = 'NOTIFICATION_UPDATING_ERROR'