
export const REMINDER_REPAYMENT_SCHEDULE = 'REMINDER_REPAYMENT_SCHEDULE'
export const REMINDER_LIST_REQUEST = 'REMINDER_LIST_REQUEST'
export const REMINDER_LIST_SUCCESS = 'REMINDER_LIST_SUCCESS'
export const REMINDER_LIST_ERROR = 'REMINDER_LIST_ERROR'
export const REMINDER_COUNT = 'REMINDER_COUNT'

export const PRICE_ADJUSTMENT_CONTRACT_FINDING_REQUEST = 'PRICE_ADJUSTMENT_CONTRACT_FINDING_REQUEST'
export const PRICE_ADJUSTMENT_CONTRACT_FINDING_SUCCESS = 'PRICE_ADJUSTMENT_CONTRACT_FINDING_SUCCESS'
export const PRICE_ADJUSTMENT_CONTRACT_FINDING_ERROR = 'PRICE_ADJUSTMENT_CONTRACT_FINDING_ERROR'