export const PROMOTION_LIST_REQUEST = 'PROMOTION_LIST_REQUEST'
export const PROMOTION_LIST_SUCCESS = 'PROMOTION_LIST_SUCCESS'
export const PROMOTION_LIST_ERROR = 'PROMOTION_LIST_ERROR'

export const PROMOTION_CREATING_REQUEST = 'PROMOTION_CREATING_REQUEST'
export const PROMOTION_CREATING_SUCCESS = 'PROMOTION_CREATING_SUCCESS'
export const PROMOTION_CREATING_ERROR = 'PROMOTION_CREATING_ERROR'

export const PROMOTION_UPDATING_REQUEST = 'PROMOTION_UPDATING_REQUEST'
export const PROMOTION_UPDATING_SUCCESS = 'PROMOTION_UPDATING_SUCCESS'
export const PROMOTION_UPDATING_ERROR = 'PROMOTION_UPDATING_ERROR'

export const PROMOTION_DELETING_REQUEST = 'PROMOTION_DELETING_REQUEST'
export const PROMOTION_DELETING_SUCCESS = 'PROMOTION_DELETING_SUCCESS'
export const PROMOTION_DELETING_ERROR = 'PROMOTION_DELETING_ERROR'

export const PROMOTION_DETAIL_FORM_REQUEST = 'PROMOTION_DETAIL_FORM_REQUEST'
export const PROMOTION_DETAIL_FORM_SUCCESS = 'PROMOTION_DETAIL_FORM_SUCCESS'
export const PROMOTION_DETAIL_FORM_ERROR = 'PROMOTION_DETAIL_FORM_ERROR'
export const TURN_OFF_PROMOTION_DETAIL_FORM = 'TURN_OFF_PROMOTION_DETAIL_FORM'

export const PROMOTION_DETAIL_REQUEST = 'PROMOTION_DETAIL_REQUEST'
export const PROMOTION_DETAIL_SUCCESS = 'PROMOTION_DETAIL_SUCCESS'
export const PROMOTION_DETAIL_ERROR = 'PROMOTION_DETAIL_ERROR'