export const CLIENT_SEARCHING_REQUEST = 'CLIENT_SEARCHING_REQUEST'
export const CLIENT_SEARCHING_SUCCESS = 'CLIENT_SEARCHING_SUCCESS'
export const CLIENT_SEARCHING_ERROR = 'CLIENT_SEARCHING_ERROR'
export const CLIENT_SEARCHING_RESET = 'CLIENT_SEARCHING_RESET'

export const CLIENT_CREATING_REQUEST = 'CLIENT_CREATING_REQUEST'
export const CLIENT_CREATING_SUCCESS = 'CLIENT_CREATING_SUCCESS'
export const CLIENT_CREATING_ERROR = 'CLIENT_CREATING_ERROR'
export const CLIENT_CREATING_RESET = 'CLIENT_CREATING_RESET'

export const CLIENT_UPDATING_REQUEST = 'CLIENT_UPDATING_REQUEST'
export const CLIENT_UPDATING_SUCCESS = 'CLIENT_UPDATING_SUCCESS'
export const CLIENT_UPDATING_ERROR = 'CLIENT_UPDATING_ERROR'
export const CLIENT_UPDATING_RESET = 'CLIENT_UPDATING_RESET'

export const CLIENT_DETAIL_REQUEST = 'CLIENT_DETAIL_REQUEST'
export const CLIENT_DETAIL_SUCCESS = 'CLIENT_DETAIL_SUCCESS'
export const CLIENT_DETAIL_ERROR = 'CLIENT_DETAIL_ERROR'
export const CLIENT_DETAIL_RESET = 'CLIENT_DETAIL_RESET'