
export const CONTRACT_REPAYMENT_SCHEDULE = 'CONTRACT_REPAYMENT_SCHEDULE'
export const CONTRACT_LIST_REQUEST = 'CONTRACT_LIST_REQUEST'
export const CONTRACT_LIST_SUCCESS = 'CONTRACT_LIST_SUCCESS'
export const CONTRACT_LIST_ERROR = 'CONTRACT_LIST_ERROR'

export const CONTRACT_CREATING_REQUEST = 'CONTRACT_CREATING_REQUEST'
export const CONTRACT_CREATING_SUCCESS = 'CONTRACT_CREATING_SUCCESS'
export const CONTRACT_CREATING_ERROR = 'CONTRACT_CREATING_ERROR'
export const CONTRACT_CREATING_RESET = 'CONTRACT_CREATING_RESET'

export const CONTRACT_REPAYING_REQUEST = 'CONTRACT_REPAYING_REQUEST'
export const CONTRACT_REPAYING_SUCCESS = 'CONTRACT_REPAYING_SUCCESS'
export const CONTRACT_REPAYING_ERROR = 'CONTRACT_REPAYING_ERROR'
export const CONTRACT_REPAYING_RESET = 'CONTRACT_REPAYING_RESET'

export const CONTRACT_DETAIL_REQUEST = 'CONTRACT_DETAIL_REQUEST'
export const CONTRACT_DETAIL_SUCCESS = 'CONTRACT_DETAIL_SUCCESS'
export const CONTRACT_DETAIL_ERROR = 'CONTRACT_DETAIL_ERROR'
export const CONTRACT_DETAIL_RESET = 'CONTRACT_DETAIL_RESET'

export const CONTRACT_UPDATING_REQUEST = 'CONTRACT_UPDATING_REQUEST'
export const CONTRACT_UPDATING_SUCCESS = 'CONTRACT_UPDATING_SUCCESS'
export const CONTRACT_UPDATING_ERROR = 'CONTRACT_UPDATING_ERROR'
export const CONTRACT_UPDATING_RESET = 'CONTRACT_UPDATING_RESET'

export const CONTRACT_APPROVING_REQUEST = 'CONTRACT_APPROVING_REQUEST'
export const CONTRACT_APPROVING_SUCCESS = 'CONTRACT_APPROVING_SUCCESS'
export const CONTRACT_APPROVING_ERROR = 'CONTRACT_APPROVING_ERROR'

export const CONTRACT_FINDING_REQUEST = 'CONTRACT_FINDING_REQUEST'
export const CONTRACT_FINDING_ERROR = 'CONTRACT_FINDING_ERROR'
export const CONTRACT_FINDING_SUCCESS = 'CONTRACT_FINDING_SUCCESS'

export const CONTRACT_DOCUMENT_REQUEST = 'CONTRACT_DOCUMENT_REQUEST'
export const CONTRACT_DOCUMENT_SUCCESS = 'CONTRACT_DOCUMENT_SUCCESS'

export const CONTRACT_SCHEDULE_REQUEST = 'CONTRACT_SCHEDULE_REQUEST'
export const CONTRACT_SCHEDULE_LIST_SUCCESS = 'CONTRACT_SCHEDULE_LIST_SUCCESS'

export const CONTRACT_TRANSACTION_REQUEST = 'CONTRACT_TRANSACTION_REQUEST'
export const CONTRACT_TRANSACTION_LIST_SUCCESS = 'CONTRACT_TRANSACTION_LIST_SUCCESS'

export const CONTRACT_SCHEDULE_TOTAL = 'CONTRACT_SCHEDULE_TOTAL'
export const CONTRACT_SUMMARY_TOTAL = 'CONTRACT_SUMMARY_TOTAL'

export const CONTRACT_SUMMARY_REQUEST = 'CONTRACT_SUMMARY_REQUEST'
export const CONTRACT_SUMMARY_RESULT = 'CONTRACT_SUMMARY_RESULT'
export const CONTRACT_SUMMARY_ERROR = 'CONTRACT_SUMMARY_ERROR'

export const CONTRACT_COUNT = 'CONTRACT_COUNT'

export const CONTRACT_REPAYMENT_REQUEST ='CONTRACT_REPAYMENT_REQUEST'
export const CONTRACT_REPAYMENT_SUCCESS ='CONTRACT_REPAYMENT_SUCCESS'
export const CONTRACT_REPAYMENT_ERROR ='CONTRACT_REPAYMENT_ERROR'

export const CHANGE_CONTRACT_REMINDER = 'CHANGE_CONTRACT_REMINDER'