
export const CUSTOMER_REPAYMENT_SCHEDULE = 'CUSTOMER_REPAYMENT_SCHEDULE'
export const CUSTOMER_LIST_REQUEST = 'CUSTOMER_LIST_REQUEST'
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS'
export const CUSTOMER_LIST_ERROR = 'CUSTOMER_LIST_ERROR'

export const CUSTOMER_DETAIL_REQUEST = 'CUSTOMER_DETAIL_REQUEST'
export const CUSTOMER_DETAIL_SUCCESS = 'CUSTOMER_DETAIL_SUCCESS'
export const CUSTOMER_DETAIL_ERROR = 'CUSTOMER_DETAIL_ERROR'

export const CUSTOMER_TH_REQUEST = 'CUSTOMER_TH_REQUEST'
export const CUSTOMER_TH_SUCCESS = 'CUSTOMER_TH_SUCCESS'
export const CUSTOMER_TH_ERROR = 'CUSTOMER_TH_ERROR'

export const CUSTOMER_FINDING_REQUEST = 'CUSTOMER_FINDING_REQUEST'
export const CUSTOMER_FINDING_ERROR = 'CUSTOMER_FINDING_ERROR'
export const CUSTOMER_FINDING_SUCCESS = 'CUSTOMER_FINDING_SUCCESS'

export const CUSTOMER_DOCUMENT_REQUEST = 'CUSTOMER_DOCUMENT_REQUEST'
export const CUSTOMER_DOCUMENT_SUCCESS = 'CUSTOMER_DOCUMENT_SUCCESS'

export const CUSTOMER_SCHEDULE_REQUEST = 'CUSTOMER_SCHEDULE_REQUEST'
export const CUSTOMER_SCHEDULE_LIST_SUCCESS = 'CUSTOMER_SCHEDULE_LIST_SUCCESS'

export const CUSTOMER_TRANSACTION_REQUEST = 'CUSTOMER_TRANSACTION_REQUEST'
export const CUSTOMER_TRANSACTION_LIST_SUCCESS = 'CUSTOMER_TRANSACTION_LIST_SUCCESS'

export const CUSTOMER_SCHEDULE_TOTAL = 'CUSTOMER_SCHEDULE_TOTAL'
export const CUSTOMER_SUMMARY_TOTAL = 'CUSTOMER_SUMMARY_TOTAL'

export const CUSTOMER_SUMMARY_REQUEST = 'CUSTOMER_SUMMARY_REQUEST'
export const CUSTOMER_SUMMARY_RESULT = 'CUSTOMER_SUMMARY_RESULT'

export const CONTRACT_ACTIVE_REQUEST = 'CONTRACT_ACTIVE_REQUEST'
export const CONTRACT_ACTIVE_RESULT = 'CONTRACT_ACTIVE_RESULT'

export const CONTRACT_CLOSE_REQUEST = 'CONTRACT_CLOSE_REQUEST'
export const CONTRACT_CLOSE_RESULT = 'CONTRACT_CLOSE_RESULT'

export const BANK_ACCOUT_REQUEST = 'BANK_ACCOUT_REQUEST'
export const BANK_ACCOUT_RESULT = 'BANK_ACCOUT_RESULT'