export const CUSTOMER_LIST_UPLOADING_REQUEST = 'CUSTOMER_LIST_UPLOADING_REQUEST'
export const CUSTOMER_LIST_UPLOADING_SUCCESS = 'CUSTOMER_LIST_UPLOADING_SUCCESS'
export const CUSTOMER_LIST_UPLOADING_ERROR = 'CUSTOMER_LIST_UPLOADING_ERROR'

export const CUSTOMER_LIST_REQUEST = 'CUSTOMER_LIST_REQUEST'
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS'
export const CUSTOMER_LIST_ERROR = 'CUSTOMER_LIST_ERROR'

export const CUSTOMER_LIST_DETAIL_REQUEST = 'CUSTOMER_LIST_DETAIL_REQUEST'
export const CUSTOMER_LIST_DETAIL_SUCCESS = 'CUSTOMER_LIST_DETAIL_SUCCESS'
export const CUSTOMER_LIST_DETAIL_ERROR = 'CUSTOMER_LIST_DETAIL_ERROR'

export const CUSTOMER_LIST_DELETING_REQUEST = 'CUSTOMER_LIST_DELETING_REQUEST'
export const CUSTOMER_LIST_DELETING_SUCCESS = 'CUSTOMER_LIST_DELETING_SUCCESS'
export const CUSTOMER_LIST_DELETING_ERROR = 'CUSTOMER_LIST_DELETING_ERROR'